version: '3'
services:
  mariadb:
    build:
      context: ./docker/mariadb
    volumes:
      - ./db:/etc/mysql
      - type: bind
        source: "./docker/log/mysql/mysql-error.log"
        target: "/var/log/mysql/mysql-error.log"
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    restart: always
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "3000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  server:
    depends_on:
      - mariadb
      - redis
    build:
      context: ./docker/server
      args:
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - GITHUB_NAME=${GITHUB_NAME}
    tty: true
    ports: 
      - 80:80
    volumes:
      - ./server:/usr/games
    networks:
      - backend

networks:
  backend:
    driver: bridge
